### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by gipi** [editorsnotes/django-licensing#1]
IMHO is missing a step in the **quick start** section: as, for example, the name and module path to import in order to use it.

Also is missing the simple step like ``pip install django-licensing``.

If it's ok I could fix this and make a pull request.

**Comment by rybesh** [comment]
Thank you for pointing this out, and a pull request would be welcomed!

**Comment by gipi** [comment]
I created a branch (as I think is shown above) and maybe I should add a templatetag to encapsulate the step for showing symbols?

**Comment by rybesh** [comment]
Your additions to the README are great, would you mind making a pull request?
https://help.github.com/articles/creating-a-pull-request/

And a template tag would also be very welcome!

**Comment by gipi** [comment]
I think i can close this now that is merged.
