### ISSUE TITLE
Problem with HTTPS

### ISSUE THREAD

**Issue by gipi** [editorsnotes/django-licensing#3]
I found out that the site (http://weloveiconfonts.com), from which the default template loads the fonts, doesn't support ``TLS`` so in secure pages an error like

    Mixed Content: The page at XXX was loaded over HTTPS, but requested an insecure stylesheet 'http://weloveiconfonts.com/api/?family=openwebicons'.
    This request has been blocked; the content must be served over HTTPS.

occurs.

The problem is that the ``https`` is not available (moreover the site itself says *This is a public gamma. Use this service for mockups, reduced test-cases or CodePens, but not on productive systems!*) so
I think the fonts should be included as static asset into the application.

If it's ok I will produce a pull request to fix this issue.

**Comment by rybesh** [comment]
Yes, I agree that the fonts should be included as assets, if we have the right to redistribute them.

**Comment by gipi** [comment]
From the [home page](https://pfefferle.github.io/openwebicons/) seems that the license is [SIL Open Font License](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL); at first glance seems to be Open Source, in particular, from the page

    OSD compatibility:The OFL complies with the ￼ Open Source Definition:
        free redistribution: #1

I have a branch gipi/django-licensing@a7ba103 with these changes and seems to work.

**Comment by rybesh** [comment]
Looks good to me!
